create table notes (
  id integer primary key generated by default as identity,
  note_name text not null,
  modified date default now(),
  folder_id integer references folders(id) on delete cascade not null,
  content text not null
);